<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rapido_BusinessEntities\Rapido_BusinessEntities.csproj" />
    <ProjectReference Include="..\Rapido_DbConnectivity\Rapido_DbConnectivity.csproj" />
  </ItemGroup>

</Project>
