<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rapido_BusinessEntities\Rapido_BusinessEntities.csproj" />
    <ProjectReference Include="..\Rapido_Repositorylayer\Rapido_Repositorylayer.csproj" />
  </ItemGroup>

</Project>
